HASH_PG_HOST=localhost
HASH_PG_PORT=5532
HASH_PG_DATABASE=hash
HASH_PG_USER=leafcolor
HASH_PG_PASSWORD=llllll

HASH_REDIS_HOST=localhost
HASH_REDIS_PORT=6380

FRONTEND_DOMAIN=m1ddns.pvtool.com:3001
NEXT_PUBLIC_API_ORIGIN=http://m1ddns.pvtool.com:5001
